### PR TITLE
Fix IE "Invalid calling object" error (attach to DOM and then compile)

### PR DESCRIPTION
**Pull request by jvmccarthy**
Hi.  I'm using ocLazyLoad in combination with angular-material and have run into an issue where using `md-tabs` in a lazy loaded module is causing "Invalid calling object" errors in IE11.  Inside of the tabs controller, elements are being saved for variables using the `getElementsByTagName()` function.  IE is invalidating the saved HTMLCollection objects once the compiled element is added to the parent DOM (this error does not occur in Firefox or Chrome).  As a fix, the content should first be added to the parent DOM and then compiled (in `ocLazyLoad.directive.js`).

I've added a test to highlight this error which can be run without the fix on my [ie_invalid_test](https://github.com/jvmccarthy/ocLazyLoad/tree/ie_invalid_test) branch.  It can be observed by running `gulp karma` (with `singleRun: false`) and then opening IE11 to the karma port.  In my tests, IE11 is also failing another test around a missing file, so you may have to focus on the specific test (change `it` to `fit`) in order to isolate this issue.

I'm also not sure why the build messed with the whitespace on the polyfill.  If you like, I can see about cleaning that up.  Also, I can file an issue for tracking and discussion, if you like.

Thank you for your time and consideration as well as your excellent work on this very important library!

### CODE REVIEW

**Comment by ocombe** [comment]
\o/ a PR with a test!!
Thanks a lot, I'll take a look at it :)

**Comment by ocombe** [comment]
Ahah looks like I just got the bug in one of my projects when I tester in IE.
Merging this, thanks :)

**Comment by ocombe** [comment]
Hmm I still have the same error on IE :-/

**Comment by jvmccarthy** [comment]
Sorry to hear that.  I'll take a look at master and see if I can reproduce the issue.  I was testing with IE11.  What version of IE were you testing with?

**Comment by ocombe** [comment]
It's ok, I fixed it in a new commit :)
I tested with IE11 as well... not sure why it was working with you and not with me, maybe a race condition.

**Comment by jvmccarthy** [comment]
Thanks for tweaking my fix.  Your changes look good.  I appreciate you working with me on this one and getting it closed quickly!

**Comment by jvmccarthy** [comment]
@ocombe Sorry to bug you, but can you also publish 1.0.8 to npm?  I'm only seeing 1.0.7 currently.  Thanks!

**Comment by ocombe** [comment]
Yes sorry, done ! Thanks for the reminder :)

**Pull request merged**
