### PR TITLE
angular 1.6 compatibility

### PR DESCRIPTION
**Pull request by alexan**

### CODE REVIEW

**Comment by ocombe** [comment]
Does this remove compatibility with previous versions of angular ?

**Comment by alexan** [comment]
no the fixes are backwards compatible

**Comment by ocombe** [comment]
Ah perfect thanks, I'm not using angular 1 anymore, so I haven't had the opportunity to test it with 1.6

**Comment by alexan** [comment]
thanks for accepting. Will you push a new version to npm?

**Comment by ocombe** [comment]
I just released 1.1.0, I think I did it right, I haven't published a new version on this repo for ages, let me know if it works

**Pull request merged**
