### PR TITLE
feat(test): allow to manually declare initModules

### PR DESCRIPTION
**Pull request by lcalvy**
Bonjour Olivier,

I find some difficulties to use ocLazyLoading in karma testing context. Karma doesn't bootstrap application and hack about angular.bootstrap isn't executed. In init phase, ocLazyLoad throw the following exception :  
No module found during bootstrap, unable to init ocLazyLoad

To allow correct init in unit test, I have included a method in angular object (can't find a better way) that allow "manual init"

Regards

### CODE REVIEW

**Comment by ocombe** [comment]
I added this error in my last commit but maybe this was a mistake. I could just remove the throw, it was just a failsafe but it is not really a necessity.
Otherwise we might find a better way to do that, could you give me the source code of a test failing to see what I can do?
If I don't find a better way I'll merge your commit

**Comment by ocombe** [comment]
Can you test the src current file, it should work with karma without the need for a special parameter :)
I'm closing this PR as it is no longer necessary.

**Comment by lcalvy** [comment]
Ok i Will try

**Comment by lcalvy** [comment]
same issue

image

**Pull request closed without merging**
