### PR TITLE
Fix issue #184

### PR DESCRIPTION
**Pull request by martinratinaud**
I did not rebuild all files are launched gulp tasks, should I ?

### CODE REVIEW

**Comment by ocombe** [comment]
It's not necessary until I release a new version. I'll do it, thanks :)

**Comment by ocombe** [comment]
Are you sure that you need to test `InvokeList` and not `invokeName` ?

**Comment by martinratinaud** [comment]
Of course, I modified the PR

**Comment by ocombe** [comment]
Thanks !

**Pull request merged**
